version: '3.1'
services:

  db:
    image: mariadb
    container_name: mariadb-srv
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=damien
      - MYSQL_PASSWORD=azerty

  adminer:
    depends_on:
      - db
    image: adminer  
    container_name: adminer
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - "50000:8080"
  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/application
    ports:
      - "30000:80"
    
volumes:
  db_data: 
